### ISSUE TITLE
Using an Organization README

### ISSUE THREAD

**Issue by castelao** [OceanGlidersCommunity/.github#1]
@soerenthomsen , this is a special repo that can provide a README.md for the organization. This is probably a better palace to introduce and welcome new members since it is shown explicitly on the organization entry page. It does the same job as the OceanGGlidersCommunity repo, but doesn't require the user to get into there to see it.

Take a look at the [organization page](https://github.com/OceanGlidersCommunity) now.

This is a relatively new feature of GitHub. Thanks to @biavillasboas for the suggestion.

What do you think? Shall we use it?

**Comment by soerenthomsen** [comment]
Looks good to me! Yes lets use it. I might try to make the Readme shorter step by step so that the repos are more visible but fine like this.

**Comment by soerenthomsen** [comment]
Edited the link in your comment now it works. I wonder whether the Readme should be in the profile folder? Just because GitHub still asks to add a Readme. 

<img width="805" alt="Screen Shot 2021-11-09 at 22 23 37" src="https://user-images.githubusercontent.com/32633545/141007175-78112869-e14b-4916-b5c0-adc581ee9145.png">

**Comment by castelao** [comment]
My understanding is that the /profile/readme is the one shown on the organization front page, and the /readme is shown in the repo .github front page.

@soerenthomsen , I'm closing this but feel free to re-open if there is more to discuss.
